
package  pointer::db::model;

use strict;
use warnings 'all';
use base 'Class::DBI::Lite::mysql';
use ASP4::ConfigLoader;
use DateTime::Format::MySQL;

my $Config = ASP4::ConfigLoader->load();
my $conn = $Config->data_connections->main;
__PACKAGE__->connection(
  $conn->dsn,
  $conn->username,
  $conn->password
);

sub after_set_up_table {
	my ($class) = @_;
	
	if($class->find_column('created_on')){
		# Auto-inflate to DateTime object:
		no strict 'refs';
		no warnings 'redefine';
		*{"$class\::_get_created_on"} = sub {
			my $s = shift;
			return DateTime::Format::MySQL->parse_datetime($s->{created_on})->set_time_zone('America/Los_Angeles');
		};
		
		*{"$class\::_set_created_on"} = sub {
			my ($s, $newval) = @_;
			no warnings 'uninitialized';
      return $newval if $newval eq $s->{created_on};
      $s->_call_triggers( "before_set_created_on", $s->{created_on}, $newval );
      $s->{__Changed}->{created_on} = {
        oldval => $s->{created_on}
      };
			return $s->{created_on} = DateTime::Format::MySQL->format_date($newval);
		};
	}
}

1;# return true:

=pod

=head1 NAME

pointer::db::model - Base class for all pointer entity classes.

=head1 SYNOPSIS

  # In your class:
  
  package pointer::db::thing;
  
  use strict;
  use warnings 'all';
  use base 'pointer::db::model';
  
  __PACKAGE__->set_up_table('things');
  
  1;# return true:

=head1 DESCRIPTION

This module was generated by /usr/local/bin/asphelper on Tue Dec 13 15:26:34 2011.

B<***IT IS SAFE to make changes to this file, as it will not be overwritten.***>.

=head1 SEE ALSO

L<Class::DBI::Lite>

=cut

